#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4

#BORDER COLORS
bspc config focused_border_color \#52B788
bspc config normal_border_color \#95d5b2

#DEFAULT
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#RULES
bspc rule -a Thorium-browser desktop='^2'
bspc rule -a VSCodium desktop='^3'
bspc rule -a Spotify desktop='^4'
bspc rule -a Thorium desktop='^2'

#AUTOSTART
sxhkd &
nitrogen --restore &
polybar &
picom &
kdeconnect-cli &
./$HOME/dotfiles/.config/customTweaks/middleScroll.sh &
